import React from 'react'
import Women from './women'
import { Product } from '../../../models/Product'

export const metadata = {
    title: 'Women-Section',
    description: 'Generated by create next app',
}

let AllProducts = []
const page = async () => {
  try {
    AllProducts = await Product.find()
    AllProducts = AllProducts.map(product => product.toObject())
  } catch (error) {
    console.error('Error fetching products:', error);
  }
  return (
    <div className='flex flex-row w-[100vw] h-[100vh] '>
      <Women category = "women" AllProducts={AllProducts}/>
    </div>
  )
}

export default page