import React from 'react'
import Women from './Women'

export const metadata = {
    title: 'Women-Section',
    description: 'Generated by create next app',
}

const Page = async () => {
  return (
    <div className='flex flex-row w-[100vw] h-[100vh] mt-[68px]'>
      <Women/>
    </div>
  )
}

export default Page