import React from 'react'
import Women from './Women'

export const metadata = {
    title: 'Women-Section',
    description: 'Generated by create next app',
}

const page = async () => {
  return (
    <div className='flex flex-row w-[100vw] h-[100vh] '>
      <Women/>
    </div>
  )
}

export default page