import React from 'react'
import Kids from './kids'
import { Product } from '../../../models/Product'
let AllProducts = []

export const metadata = {
    title: 'Kids-section',
    description: 'Generated by create next app',
}

const page = async () => {
  try {
    AllProducts = await Product.find()
    AllProducts = AllProducts.map(product => product.toObject())
  } catch (error) {
    console.error('Error fetching products:', error);
  }
  return (
    <div className='flex flex-row w-[100vw] h-[100vh] '>
      <Kids category = "kids" AllProducts={AllProducts}/>
    </div>
  )
}

export default page