import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import { ClerkProvider } from '@clerk/nextjs'
import { connectDb } from '../utils/connectdb'
import {CreateUser} from "../utils/userCreation"
import {ToastContainer} from "../app/components/nextToast"
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
          <body className={inter.className}>
              {connectDb()}
              {CreateUser()}
              <Navbar/>
              <ToastContainer/>
                {children}
          </body>
      </html>
    </ClerkProvider>
  )
}
