import React from 'react'
import Men from './Men'

export const metadata = {
  title: 'Men-Section',
  description: 'Generated by create next app',
}


const Page = async () => {
  return (
    <div className='flex flex-row w-[100vw] h-[100vh] mt-[68px]'>
      <Men/>
    </div>
  )
}

export default Page